name: ドキュメント更新
description: ドキュメントの追加・修正・改善を提案
body:
  - type: textarea
    id: doc_update
    attributes:
      label: 更新内容の概要
      placeholder: ここにドキュメントの更新内容を入力してください
    validations:
      required: true
  - type: textarea
    id: related_sections
    attributes:
      label: 関連セクション
      placeholder: 更新対象のドキュメントのセクションやファイルを入力してください
  - type: textarea
    id: motivation
    attributes:
      label: 背景・目的
      placeholder: なぜこの更新が必要か、どの問題を解決するかを入力してください
assignees:
  - shimomo
labels: ["documentation"]
title: ここにドキュメント更新のタイトルを入力
type: Documentation
